### ISSUE TITLE
Symfony 4.3 User Deprecated

### ISSUE THREAD

**Issue by gam6itko** [symfony/acl-bundle#18]
- A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.

- The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "acl" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.

**Comment by XWB** [comment]
Was already fixed in https://github.com/symfony/acl-bundle/pull/16

Perhaps @fabpot is willing to tag a new release?

**Comment by fabpot** [comment]
Done
