### ISSUE TITLE
Followed the examples, but got: Service "security.acl.provider" not found

### ISSUE THREAD

**Issue by glennthehuman** [symfony/acl-bundle#20]
I followed the example: https://github.com/symfony/acl-bundle/blob/master/src/Resources/doc/index.rst
`
class BlogController extends Controller
{
    // ...

    public function addCommentAction(Post $post)
    {
        $comment = new Comment();

        // ... setup $form, and submit data

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($comment);
            $entityManager->flush();

            // creating the ACL
            $aclProvider = $this->get('security.acl.provider');
            $objectIdentity = ObjectIdentity::fromDomainObject($comment);
            $acl = $aclProvider->createAcl($objectIdentity);

            // retrieving the security identity of the currently logged-in user
            $tokenStorage = $this->get('security.token_storage');
            $user = $tokenStorage->getToken()->getUser();
            $securityIdentity = UserSecurityIdentity::fromAccount($user);

            // grant owner access
            $acl->insertObjectAce($securityIdentity, MaskBuilder::MASK_OWNER);
            $aclProvider->updateAcl($acl);
        }
    }
}
`

But after submitting the form, I got:

> Service "security.acl.provider" not found: even though it exists in the app's container, the container inside "App\Controller\Web\BlogController" is a smaller service locator that only knows about the "doctrine", "form.factory", "http_kernel", "parameter_bag", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "session" and "twig" services. Unless you need extra laziness, try using dependency injection instead. Otherwise, you need to declare it using "BlogController::getSubscribedServices()".

**Comment by glennthehuman** [comment]
SOLVED:
I previously extended `Symfony\Bundle\FrameworkBundle\Controller\AbstractController`. It should be `Symfony\Bundle\FrameworkBundle\Controller\Controller`

**Comment by AlexandreKilian** [comment]
Got this issue, only there is no "Controller"-Class in `Symfony\Bundle\FrameworkBundle\Controller`anymore (5.2)
Changelog from 5.0
> * Removed `Controller`, use `AbstractController` instead

I know, inject it with `(AclProviderInterface $aclProvider)`, just saying the docs aren't up to date
