### ISSUE TITLE
Tests are broken since symfony/dependency-injection:4.4

### ISSUE THREAD

**Issue by ekosogin** [symfony/acl-bundle#23]
I've tried to update dependencies of acl-bundle to sf5 but it was unsuccessful. Since tests are broken from symfony/dependency-injection:4.4.0. Commit which affected tests - 
`https://github.com/symfony/dependency-injection/commit/ddb02286fb427dc6aba02cabc150f21b40aeb349` (@nicolas-grekas )

Example of error message from tests
1) Symfony\Bundle\AclBundle\Tests\DependencyInjection\PhpCompleteConfigurationTest::testAcl
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "security.acl.security_identity_retrieval_strategy" has a dependency on a non-existent service "security.role_hierarchy".

acl-bundle/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:86
acl-bundle/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:82
acl-bundle/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:49
acl-bundle/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:91
acl-bundle/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:49
acl-bundle/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:82
acl-bundle/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:49
acl-bundle/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:46
acl-bundle/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:40
acl-bundle/vendor/symfony/dependency-injection/Compiler/Compiler.php:94
acl-bundle/vendor/symfony/dependency-injection/ContainerBuilder.php:762
acl-bundle/tests/DependencyInjection/CompleteConfigurationTest.php:56
acl-bundle/tests/DependencyInjection/CompleteConfigurationTest.php:27

**Comment by fabpot** [comment]
fixed now in master
