### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by machek** [symfony/acl-bundle#6]
Is there "symfony/acl-bundle" documentation for Symfony4?

GitHub page points to Symfony documentation and Symfony back to GitHub. It looks official documentation is somehow missing.

**Comment by kevinpapst** [comment]
Had the same issue while searching for the docs, see the reason here: 
https://github.com/symfony/symfony-docs/issues/8906

Stick to the docs of 3.4 unless we get more infos:
https://symfony.com/doc/3.4/security/acl.html
